// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify CLI.
const awsconfig = {
    Auth: {
        identityPoolId: 'us-east-1:03c8cb28-485e-42a1-8353-f53c90d3f284',
        region: 'us-east-1',
    },
    Storage: {
        bucket: 'group-10-testing-bucket',
        region: 'us-east-1',
        identityPoolId: 'us-east-1:03c8cb28-485e-42a1-8353-f53c90d3f284',
    },
};
export default awsconfig;
